### ISSUE TITLE
eta on arm and disarm apis

### ISSUE THREAD

**Issue by samsel** [jhurliman/node-frontpoint#1]
@jhurliman is there an eta on the arm and disarm api implementations?

**Comment by jhurliman** [comment]
Hi, apologies for the radio silence on this. I haven't had time in the past few months to complete this project, but I plan on picking it up again this week and hopefully getting the arm/disarm functionality to a usable place.

**Comment by jhurliman** [comment]
You can give the https://github.com/jhurliman/node-frontpoint/tree/jh-armdisarm branch a shot. I'll test it myself in the next day or so and publish a new version if everything is working as expected.

**Comment by jhurliman** [comment]
Ok, tested and working via PR #2. I added some API docs as well and fixed a code error in the usage example.

**Comment by samsel** [comment]
thank you @jhurliman this is awesome
